import json

def create_markdown_cell(source):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source if isinstance(source, list) else [source]
    }

def create_code_cell(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": source if isinstance(source, list) else [source]
    }

# Create all cells
cells = [
    # Introduction
    create_markdown_cell([
        "# 🎙️ Voice Cloning with Tortoise TTS\n",
        "\n",
        "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/juanvolpe/voice2/blob/master/voice_cloning.ipynb)\n",
        "\n",
        "This notebook allows you to clone voices using Tortoise TTS, supporting multiple languages and quality presets.\n",
        "\n",
        "## 🎯 Features\n",
        "- Voice cloning with Tortoise TTS\n",
        "- Support for 13 languages\n",
        "- Multiple quality presets\n",
        "- GPU acceleration\n",
        "- Easy voice sample management\n",
        "\n",
        "## 📝 Prerequisites\n",
        "1. **Google Colab**: Make sure you're running this in Colab with GPU runtime\n",
        "2. **Voice Samples**: Prepare WAV/MP3 files (5-10 seconds each)\n",
        "3. **Hugging Face Token**: Will be loaded from Colab secrets"
    ]),

    # Section 1: Setup
    create_markdown_cell([
        "# Section 1: Setup 🔧\n",
        "\n",
        "First, ensure you're using a GPU runtime:\n",
        "1. Click `Runtime` in the menu\n",
        "2. Select `Change runtime type`\n",
        "3. Choose `GPU` from the hardware accelerator dropdown\n",
        "4. Click `Save`"
    ]),

    # GPU Check
    create_code_cell([
        "# Check GPU availability\n",
        "import torch\n",
        "print(\"🔍 Checking GPU configuration...\")\n",
        "print(f\"GPU Available: {'✅' if torch.cuda.is_available() else '❌'}\")\n",
        "if torch.cuda.is_available():\n",
        "    print(f\"Device: {torch.cuda.get_device_name(0)}\")\n",
        "    print(f\"CUDA Version: {torch.version.cuda}\")\n",
        "else:\n",
        "    print(\"\\n⚠️ No GPU detected! Please change runtime to GPU for better performance:\")\n",
        "    print(\"1. Runtime > Change runtime type\")\n",
        "    print(\"2. Select GPU from Hardware accelerator dropdown\")\n",
        "    print(\"3. Click Save and restart runtime\")"
    ]),

    # Dependencies Installation (UPDATED)
    create_code_cell([
        "# Install dependencies with specific versions\n",
        "print(\"📦 Installing dependencies...\")\n",
        "\n",
        "try:\n",
        "    # First uninstall any existing installations to avoid conflicts\n",
        "    !pip uninstall -y torch torchaudio torchvision transformers numpy tokenizers tortoise-tts\n",
        "    print(\"✅ Cleaned existing installations\")\n",
        "    \n",
        "    # Install CUDA toolkit dependencies\n",
        "    !apt-get -y update\n",
        "    !apt-get -y install cuda-toolkit-11-8\n",
        "    print(\"✅ CUDA toolkit installed\")\n",
        "    \n",
        "    # Install PyTorch ecosystem\n",
        "    !pip install --quiet torch==2.1.0 torchaudio==2.1.0 torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cu118\n",
        "    print(\"✅ PyTorch ecosystem installed\")\n",
        "    \n",
        "    # Install base dependencies\n",
        "    !pip install --quiet numpy==1.26.0\n",
        "    !pip install --quiet \"transformers>=4.34.0,<4.35.0\"\n",
        "    !pip install --quiet \"tokenizers>=0.14.0,<0.15.0\"\n",
        "    print(\"✅ Base dependencies installed\")\n",
        "    \n",
        "    # Install other dependencies\n",
        "    !pip install --quiet librosa==0.10.1\n",
        "    !pip install --quiet unidecode==1.3.6 inflect==7.0.0 tqdm==4.66.1\n",
        "    print(\"✅ Additional dependencies installed\")\n",
        "    \n",
        "    # Install Tortoise TTS\n",
        "    !pip install --quiet git+https://github.com/neonbjb/tortoise-tts.git\n",
        "    print(\"✅ Tortoise TTS installed\")\n",
        "    \n",
        "    print(\"\\n🔄 Verifying installations...\")\n",
        "    import torch\n",
        "    import transformers\n",
        "    import numpy\n",
        "    import tokenizers\n",
        "    print(f\"PyTorch: {torch.__version__}\")\n",
        "    print(f\"Transformers: {transformers.__version__}\")\n",
        "    print(f\"NumPy: {numpy.__version__}\")\n",
        "    print(f\"Tokenizers: {tokenizers.__version__}\")\n",
        "    \n",
        "    # Verify CUDA is working\n",
        "    if torch.cuda.is_available():\n",
        "        print(f\"CUDA available: Yes (Version {torch.version.cuda})\")\n",
        "        # Test CUDA with a simple operation\n",
        "        x = torch.rand(5, 3)\n",
        "        print(\"CUDA test successful: \", x.cuda().device)\n",
        "    else:\n",
        "        print(\"⚠️ CUDA not available. Please check GPU runtime settings.\")\n",
        "    \n",
        "except Exception as e:\n",
        "    print(f\"\\n❌ Error during installation: {str(e)}\")\n",
        "    print(\"Please try restarting the runtime and running this cell again.\")\n",
        "    raise e\n",
        "\n",
        "# Force restart runtime to ensure clean environment\n",
        "print(\"\\n⚠️ Restarting runtime to apply changes...\")\n",
        "import os\n",
        "os.kill(os.getpid(), 9)\n",
        "\n",
        "# The following code will run after restart\n",
        "print(\"\\n🔄 Importing dependencies...\")\n",
        "import os\n",
        "import torch\n",
        "import torchaudio\n",
        "from IPython.display import Audio, display\n",
        "from google.colab import files, userdata\n",
        "\n",
        "# Import Tortoise TTS\n",
        "from tortoise.api import TextToSpeech\n",
        "from tortoise.utils.audio import load_audio, load_voice, load_voices\n",
        "print(\"\\n✅ Tortoise TTS imported successfully!\")\n",
        "\n",
        "# Set up Hugging Face token\n",
        "try:\n",
        "    hf_token = userdata.get('HF_TOKEN')\n",
        "    if hf_token:\n",
        "        os.environ['HF_TOKEN'] = hf_token\n",
        "        from huggingface_hub import login\n",
        "        login(token=hf_token)\n",
        "        print(\"✅ Hugging Face token configured successfully!\")\n",
        "    else:\n",
        "        print(\"⚠️ HF_TOKEN not found in Colab secrets\")\n",
        "        print(\"Some features might be limited. Add HF_TOKEN to your Colab secrets if needed.\")\n",
        "except Exception as e:\n",
        "    print(f\"❌ Error configuring Hugging Face token: {str(e)}\")\n",
        "\n",
        "# Initialize device\n",
        "device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
        "print(f\"\\n🖥️ Using device: {device}\")\n",
        "\n",
        "print(\"\\n🚀 Setup complete! Ready to proceed with voice cloning.\")"
    ]),

    # Section 2: Voice Samples
    create_markdown_cell([
        "# Section 2: Voice Sample Management 🎤\n",
        "\n",
        "## Voice Sample Requirements\n",
        "For best results, your voice samples should:\n",
        "- Be in WAV or MP3 format\n",
        "- Last 5-10 seconds each\n",
        "- Contain clear speech with minimal background noise\n",
        "- Have consistent voice tone and quality\n",
        "- Be recorded in a quiet environment\n",
        "\n",
        "## Sample Management\n",
        "The system will:\n",
        "1. Create a directory for your samples\n",
        "2. Validate file formats\n",
        "3. Check audio quality\n",
        "4. Analyze sample duration\n",
        "5. Provide feedback on each sample"
    ]),

    # Voice Sample Upload
    create_code_cell([
        "class VoiceSampleManager:\n",
        "    def __init__(self, sample_dir='voice_samples'):\n",
        "        \"\"\"Initialize the voice sample manager\"\"\"\n",
        "        self.sample_dir = sample_dir\n",
        "        self.samples = []\n",
        "        os.makedirs(sample_dir, exist_ok=True)\n",
        "        print(f\"📁 Sample directory ready: {sample_dir}\")\n",
        "        \n",
        "    def upload_samples(self):\n",
        "        \"\"\"Upload and validate voice samples\"\"\"\n",
        "        print(\"\\n📂 Select your voice sample files (WAV or MP3)\")\n",
        "        uploaded = files.upload()\n",
        "        \n",
        "        for filename in uploaded.keys():\n",
        "            if filename.lower().endswith(('.wav', '.mp3')):\n",
        "                filepath = os.path.join(self.sample_dir, filename)\n",
        "                os.rename(filename, filepath)\n",
        "                print(f\"✅ Uploaded: {filename}\")\n",
        "                self.samples.append(filepath)\n",
        "            else:\n",
        "                print(f\"❌ Skipped: {filename} (not a WAV or MP3 file)\")\n",
        "    \n",
        "    def analyze_samples(self):\n",
        "        \"\"\"Analyze uploaded samples for quality and duration\"\"\"\n",
        "        print(\"\\n🔍 Analyzing voice samples...\")\n",
        "        valid_samples = []\n",
        "        \n",
        "        for sample in os.listdir(self.sample_dir):\n",
        "            filepath = os.path.join(self.sample_dir, sample)\n",
        "            try:\n",
        "                # Load and analyze audio\n",
        "                waveform, sample_rate = torchaudio.load(filepath)\n",
        "                duration = waveform.size(1) / sample_rate\n",
        "                \n",
        "                # Print analysis\n",
        "                print(f\"\\n📊 Analysis for {sample}:\")\n",
        "                print(f\"- Duration: {duration:.1f} seconds\")\n",
        "                print(f\"- Channels: {waveform.size(0)}\")\n",
        "                print(f\"- Sample Rate: {sample_rate} Hz\")\n",
        "                \n",
        "                # Add recommendations\n",
        "                if duration < 5:\n",
        "                    print(\"⚠️ Sample is shorter than recommended (5-10 seconds)\")\n",
        "                elif duration > 10:\n",
        "                    print(\"⚠️ Sample is longer than recommended (5-10 seconds)\")\n",
        "                else:\n",
        "                    print(\"✅ Duration is within recommended range\")\n",
        "                \n",
        "                valid_samples.append(filepath)\n",
        "                \n",
        "            except Exception as e:\n",
        "                print(f\"❌ Error analyzing {sample}: {str(e)}\")\n",
        "        \n",
        "        return valid_samples\n",
        "\n",
        "# Create manager and handle samples\n",
        "voice_manager = VoiceSampleManager()\n",
        "voice_manager.upload_samples()\n",
        "valid_samples = voice_manager.analyze_samples()\n",
        "\n",
        "# Summary\n",
        "print(f\"\\n📝 Summary:\")\n",
        "print(f\"- Total samples: {len(os.listdir(voice_manager.sample_dir))}\")\n",
        "print(f\"- Valid samples: {len(valid_samples)}\")\n",
        "if len(valid_samples) == 0:\n",
        "    print(\"\\n⚠️ No valid samples found. Please upload some voice samples.\")"
    ]),

    # Section 3: Configuration
    create_markdown_cell([
        "# Section 3: Configuration ⚙️\n",
        "\n",
        "## Available Settings\n",
        "\n",
        "### Quality Presets\n",
        "Each preset balances speed vs quality:\n",
        "- `ultra_fast`: Fastest generation, lower quality\n",
        "- `fast`: Quick generation with decent quality\n",
        "- `standard`: Balanced speed and quality\n",
        "- `high_quality`: Best quality, slower generation\n",
        "\n",
        "### Language Support\n",
        "Supported languages for input and output:\n",
        "- English (en), Spanish (es), French (fr)\n",
        "- German (de), Italian (it), Portuguese (pt)\n",
        "- Polish (pl), Turkish (tr), Russian (ru)\n",
        "- Dutch (nl), Czech (cs), Arabic (ar)\n",
        "- Chinese (Simplified) (zh-cn)\n",
        "\n",
        "> Note: Higher quality presets require more VRAM and processing time. Start with 'standard' and adjust based on results."
    ]),

    # Voice Generation Setup
    create_code_cell([
        "class VoiceGenerator:\n",
        "    QUALITY_PRESETS = ['ultra_fast', 'fast', 'standard', 'high_quality']\n",
        "    SUPPORTED_LANGUAGES = ['en', 'es', 'fr', 'de', 'it', 'pt', 'pl', 'tr', 'ru', 'nl', 'cs', 'ar', 'zh-cn']\n",
        "    \n",
        "    def __init__(self, device='cuda'):\n",
        "        \"\"\"Initialize the voice generator\"\"\"\n",
        "        self.device = device\n",
        "        self.tts = TextToSpeech(device=device)\n",
        "        print(f\"✅ Voice Generator initialized on {device}\")\n",
        "    \n",
        "    def validate_settings(self, quality_preset, input_lang, output_lang):\n",
        "        \"\"\"Validate generation settings\"\"\"\n",
        "        if quality_preset not in self.QUALITY_PRESETS:\n",
        "            raise ValueError(f\"Quality preset must be one of {self.QUALITY_PRESETS}\")\n",
        "        \n",
        "        if input_lang not in self.SUPPORTED_LANGUAGES:\n",
        "            raise ValueError(f\"Input language must be one of {self.SUPPORTED_LANGUAGES}\")\n",
        "            \n",
        "        if output_lang not in self.SUPPORTED_LANGUAGES:\n",
        "            raise ValueError(f\"Output language must be one of {self.SUPPORTED_LANGUAGES}\")\n",
        "    \n",
        "    def generate_speech(self, text, voice_samples, quality_preset='standard', \n",
        "                       input_lang='en', output_lang='en'):\n",
        "        \"\"\"Generate speech using provided samples and settings\"\"\"\n",
        "        # Validate settings\n",
        "        self.validate_settings(quality_preset, input_lang, output_lang)\n",
        "        \n",
        "        # Load and process voice samples\n",
        "        processed_samples = []\n",
        "        for sample_path in voice_samples:\n",
        "            try:\n",
        "                audio = load_audio(sample_path, 22050)\n",
        "                processed_samples.append(audio)\n",
        "            except Exception as e:\n",
        "                print(f\"❌ Error processing {sample_path}: {str(e)}\")\n",
        "                continue\n",
        "        \n",
        "        if not processed_samples:\n",
        "            raise ValueError(\"No valid voice samples available\")\n",
        "        \n",
        "        # Generate speech\n",
        "        print(f\"\\n🎵 Generating speech with {quality_preset} quality...\")\n",
        "        gen_audio = self.tts.tts_with_preset(\n",
        "            text,\n",
        "            voice_samples=processed_samples,\n",
        "            preset=quality_preset,\n",
        "            k=1,\n",
        "            use_deterministic_seed=True\n",
        "        )\n",
        "        \n",
        "        # Save and return audio\n",
        "        output_path = 'generated_speech.wav'\n",
        "        torchaudio.save(output_path, gen_audio.squeeze(0).cpu(), 24000)\n",
        "        print(f\"✅ Speech generated and saved as {output_path}\")\n",
        "        \n",
        "        return Audio(output_path)\n",
        "\n",
        "# Initialize generator\n",
        "generator = VoiceGenerator(device=device)\n",
        "\n",
        "# Print available options\n",
        "print(\"\\n📋 Available Settings:\")\n",
        "print(\"\\nQuality Presets:\")\n",
        "for preset in generator.QUALITY_PRESETS:\n",
        "    print(f\"- {preset}\")\n",
        "\n",
        "print(\"\\nSupported Languages:\")\n",
        "for lang in generator.SUPPORTED_LANGUAGES:\n",
        "    print(f\"- {lang}\")"
    ]),

    # Section 4: Generation
    create_markdown_cell([
        "# Section 4: Generate and Test Speech 🔊\n",
        "\n",
        "## Generation Parameters\n",
        "- **Text**: The text you want to convert to speech\n",
        "- **Quality**: Choose from available presets\n",
        "- **Languages**: Select input/output languages\n",
        "- **Voice Samples**: Uses previously uploaded samples\n",
        "\n",
        "> Tip: Start with a short test phrase to verify quality before generating longer content."
    ]),

    # Test Generation
    create_code_cell([
        "def generate_test_speech(text, quality='standard', input_lang='en', output_lang='en'):\n",
        "    \"\"\"Generate a test speech sample\"\"\"\n",
        "    try:\n",
        "        # Get validated samples\n",
        "        samples = voice_manager.analyze_samples()\n",
        "        if not samples:\n",
        "            return print(\"❌ No valid voice samples found. Please upload samples first.\")\n",
        "        \n",
        "        # Generate and display speech\n",
        "        print(f\"\\n🎯 Generating speech with following settings:\")\n",
        "        print(f\"- Quality: {quality}\")\n",
        "        print(f\"- Input Language: {input_lang}\")\n",
        "        print(f\"- Output Language: {output_lang}\")\n",
        "        print(f\"- Text: \\\"{text}\\\"\")\n",
        "        \n",
        "        audio = generator.generate_speech(\n",
        "            text=text,\n",
        "            voice_samples=samples,\n",
        "            quality_preset=quality,\n",
        "            input_lang=input_lang,\n",
        "            output_lang=output_lang\n",
        "        )\n",
        "        \n",
        "        print(\"\\n🔊 Playing generated audio...\")\n",
        "        display(audio)\n",
        "        \n",
        "        print(\"\\n💾 To download the generated audio:\")\n",
        "        print(\"1. Find 'generated_speech.wav' in the file browser\")\n",
        "        print(\"2. Right-click and select 'Download'\")\n",
        "        \n",
        "    except Exception as e:\n",
        "        print(f\"❌ Error generating speech: {str(e)}\")\n",
        "\n",
        "# Test with a short phrase\n",
        "test_text = \"Hello, this is a test of voice cloning using Tortoise TTS.\"\n",
        "generate_test_speech(\n",
        "    text=test_text,\n",
        "    quality='standard',  # Try: 'ultra_fast', 'fast', 'standard', 'high_quality'\n",
        "    input_lang='en',\n",
        "    output_lang='en'\n",
        ")"
    ]),

    # Section 5: Troubleshooting
    create_markdown_cell([
        "# Section 5: Troubleshooting ⚠️\n",
        "\n",
        "## Common Issues and Solutions\n",
        "\n",
        "### 1. Runtime Issues\n",
        "- **GPU Not Available**\n",
        "  - Check Runtime > Change runtime type\n",
        "  - Select GPU from hardware accelerator\n",
        "  - Restart runtime after changes\n",
        "\n",
        "- **Runtime Disconnected**\n",
        "  - Save your work frequently\n",
        "  - Rerun setup cells after reconnection\n",
        "  - Keep Colab tab active\n",
        "\n",
        "### 2. Voice Sample Issues\n",
        "- **Invalid Format**\n",
        "  - Use WAV or MP3 files only\n",
        "  - Check file extensions\n",
        "  - Ensure files aren't corrupted\n",
        "\n",
        "- **Quality Problems**\n",
        "  - Record in a quiet environment\n",
        "  - Use a good microphone\n",
        "  - Keep consistent voice tone\n",
        "  - Stay within 5-10 seconds per sample\n",
        "\n",
        "### 3. Generation Issues\n",
        "- **Out of Memory**\n",
        "  - Try a lower quality preset\n",
        "  - Reduce number of voice samples\n",
        "  - Clear runtime memory (Runtime > Restart runtime)\n",
        "\n",
        "- **Poor Quality Output**\n",
        "  - Use higher quality preset\n",
        "  - Provide clearer voice samples\n",
        "  - Check input/output language settings\n",
        "\n",
        "### 4. File Management\n",
        "- **Lost Files**\n",
        "  - Download generated audio immediately\n",
        "  - Keep backup of voice samples\n",
        "  - Save notebook frequently\n",
        "\n",
        "- **Storage Full**\n",
        "  - Clear old generated files\n",
        "  - Remove unused voice samples\n",
        "  - Reset runtime if needed\n",
        "\n",
        "## Getting Help\n",
        "- Check [Tortoise TTS Documentation](https://github.com/neonbjb/tortoise-tts)\n",
        "- Visit [Google Colab FAQs](https://research.google.com/colaboratory/faq.html)\n",
        "- Review error messages carefully\n",
        "- Try the suggested solutions above"
    ])
]

# Create the notebook
notebook = {
    "cells": cells,
    "metadata": {
        "accelerator": "GPU",
        "colab": {
            "name": "Voice Cloning with Tortoise TTS",
            "provenance": []
        },
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

# Write the notebook to a file
with open('voice_cloning.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2) 